//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/arch/core/core-common/src/main/java/androidx/arch/core/util/Function.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxArchCoreUtilFunction")
#ifdef RESTRICT_AndroidxArchCoreUtilFunction
#define INCLUDE_ALL_AndroidxArchCoreUtilFunction 0
#else
#define INCLUDE_ALL_AndroidxArchCoreUtilFunction 1
#endif
#undef RESTRICT_AndroidxArchCoreUtilFunction

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXFunction_) && (INCLUDE_ALL_AndroidxArchCoreUtilFunction || defined(INCLUDE_AXFunction))
#define AXFunction_

@protocol AXFunction < JavaObject >

- (id)applyWithId:(id)input;

@end

J2OBJC_EMPTY_STATIC_INIT(AXFunction)

J2OBJC_TYPE_LITERAL_HEADER(AXFunction)

#define AndroidxArchCoreUtilFunction AXFunction

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxArchCoreUtilFunction")
