//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/annotation/annotation/src/main/java/androidx/annotation/AnimatorRes.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxAnnotationAnimatorRes")
#ifdef RESTRICT_AndroidxAnnotationAnimatorRes
#define INCLUDE_ALL_AndroidxAnnotationAnimatorRes 0
#else
#define INCLUDE_ALL_AndroidxAnnotationAnimatorRes 1
#endif
#undef RESTRICT_AndroidxAnnotationAnimatorRes

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXAnimatorRes_) && (INCLUDE_ALL_AndroidxAnnotationAnimatorRes || defined(INCLUDE_AXAnimatorRes))
#define AXAnimatorRes_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol AXAnimatorRes < JavaLangAnnotationAnnotation >

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface AXAnimatorRes : NSObject < AXAnimatorRes >

@end

J2OBJC_EMPTY_STATIC_INIT(AXAnimatorRes)

FOUNDATION_EXPORT id<AXAnimatorRes> create_AXAnimatorRes(void);

J2OBJC_TYPE_LITERAL_HEADER(AXAnimatorRes)

#define AndroidxAnnotationAnimatorRes AXAnimatorRes

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxAnnotationAnimatorRes")
