//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/annotation/annotation/src/main/java/androidx/annotation/AnyRes.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxAnnotationAnyRes")
#ifdef RESTRICT_AndroidxAnnotationAnyRes
#define INCLUDE_ALL_AndroidxAnnotationAnyRes 0
#else
#define INCLUDE_ALL_AndroidxAnnotationAnyRes 1
#endif
#undef RESTRICT_AndroidxAnnotationAnyRes

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXAnyRes_) && (INCLUDE_ALL_AndroidxAnnotationAnyRes || defined(INCLUDE_AXAnyRes))
#define AXAnyRes_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol AXAnyRes < JavaLangAnnotationAnnotation >

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface AXAnyRes : NSObject < AXAnyRes >

@end

J2OBJC_EMPTY_STATIC_INIT(AXAnyRes)

FOUNDATION_EXPORT id<AXAnyRes> create_AXAnyRes(void);

J2OBJC_TYPE_LITERAL_HEADER(AXAnyRes)

#define AndroidxAnnotationAnyRes AXAnyRes

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxAnnotationAnyRes")
