//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/annotation/annotation/src/main/java/androidx/annotation/AnyThread.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxAnnotationAnyThread")
#ifdef RESTRICT_AndroidxAnnotationAnyThread
#define INCLUDE_ALL_AndroidxAnnotationAnyThread 0
#else
#define INCLUDE_ALL_AndroidxAnnotationAnyThread 1
#endif
#undef RESTRICT_AndroidxAnnotationAnyThread

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXAnyThread_) && (INCLUDE_ALL_AndroidxAnnotationAnyThread || defined(INCLUDE_AXAnyThread))
#define AXAnyThread_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol AXAnyThread < JavaLangAnnotationAnnotation >

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface AXAnyThread : NSObject < AXAnyThread >

@end

J2OBJC_EMPTY_STATIC_INIT(AXAnyThread)

FOUNDATION_EXPORT id<AXAnyThread> create_AXAnyThread(void);

J2OBJC_TYPE_LITERAL_HEADER(AXAnyThread)

#define AndroidxAnnotationAnyThread AXAnyThread

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxAnnotationAnyThread")
