//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/annotation/annotation/src/main/java/androidx/annotation/BoolRes.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxAnnotationBoolRes")
#ifdef RESTRICT_AndroidxAnnotationBoolRes
#define INCLUDE_ALL_AndroidxAnnotationBoolRes 0
#else
#define INCLUDE_ALL_AndroidxAnnotationBoolRes 1
#endif
#undef RESTRICT_AndroidxAnnotationBoolRes

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXBoolRes_) && (INCLUDE_ALL_AndroidxAnnotationBoolRes || defined(INCLUDE_AXBoolRes))
#define AXBoolRes_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol AXBoolRes < JavaLangAnnotationAnnotation >

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface AXBoolRes : NSObject < AXBoolRes >

@end

J2OBJC_EMPTY_STATIC_INIT(AXBoolRes)

FOUNDATION_EXPORT id<AXBoolRes> create_AXBoolRes(void);

J2OBJC_TYPE_LITERAL_HEADER(AXBoolRes)

#define AndroidxAnnotationBoolRes AXBoolRes

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxAnnotationBoolRes")
