//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/annotation/annotation/src/main/java/androidx/annotation/CallSuper.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxAnnotationCallSuper")
#ifdef RESTRICT_AndroidxAnnotationCallSuper
#define INCLUDE_ALL_AndroidxAnnotationCallSuper 0
#else
#define INCLUDE_ALL_AndroidxAnnotationCallSuper 1
#endif
#undef RESTRICT_AndroidxAnnotationCallSuper

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXCallSuper_) && (INCLUDE_ALL_AndroidxAnnotationCallSuper || defined(INCLUDE_AXCallSuper))
#define AXCallSuper_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol AXCallSuper < JavaLangAnnotationAnnotation >

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface AXCallSuper : NSObject < AXCallSuper >

@end

J2OBJC_EMPTY_STATIC_INIT(AXCallSuper)

FOUNDATION_EXPORT id<AXCallSuper> create_AXCallSuper(void);

J2OBJC_TYPE_LITERAL_HEADER(AXCallSuper)

#define AndroidxAnnotationCallSuper AXCallSuper

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxAnnotationCallSuper")
