//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/annotation/annotation/src/main/java/androidx/annotation/ChecksSdkIntAtLeast.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxAnnotationChecksSdkIntAtLeast")
#ifdef RESTRICT_AndroidxAnnotationChecksSdkIntAtLeast
#define INCLUDE_ALL_AndroidxAnnotationChecksSdkIntAtLeast 0
#else
#define INCLUDE_ALL_AndroidxAnnotationChecksSdkIntAtLeast 1
#endif
#undef RESTRICT_AndroidxAnnotationChecksSdkIntAtLeast

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXChecksSdkIntAtLeast_) && (INCLUDE_ALL_AndroidxAnnotationChecksSdkIntAtLeast || defined(INCLUDE_AXChecksSdkIntAtLeast))
#define AXChecksSdkIntAtLeast_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol AXChecksSdkIntAtLeast < JavaLangAnnotationAnnotation >

@property (readonly) jint api;
@property (readonly) NSString *codename;
@property (readonly) jint parameter;
@property (readonly) jint lambda;

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface AXChecksSdkIntAtLeast : NSObject < AXChecksSdkIntAtLeast > {
 @public
  jint api_;
  NSString *codename_;
  jint parameter_;
  jint lambda_;
}

@end

J2OBJC_EMPTY_STATIC_INIT(AXChecksSdkIntAtLeast)

FOUNDATION_EXPORT id<AXChecksSdkIntAtLeast> create_AXChecksSdkIntAtLeast(jint api, NSString *codename, jint lambda, jint parameter);

J2OBJC_TYPE_LITERAL_HEADER(AXChecksSdkIntAtLeast)

#define AndroidxAnnotationChecksSdkIntAtLeast AXChecksSdkIntAtLeast

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxAnnotationChecksSdkIntAtLeast")
