//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/annotation/annotation/src/main/java/androidx/annotation/ColorLong.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxAnnotationColorLong")
#ifdef RESTRICT_AndroidxAnnotationColorLong
#define INCLUDE_ALL_AndroidxAnnotationColorLong 0
#else
#define INCLUDE_ALL_AndroidxAnnotationColorLong 1
#endif
#undef RESTRICT_AndroidxAnnotationColorLong

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXColorLong_) && (INCLUDE_ALL_AndroidxAnnotationColorLong || defined(INCLUDE_AXColorLong))
#define AXColorLong_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@protocol AXColorLong < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(AXColorLong)

J2OBJC_TYPE_LITERAL_HEADER(AXColorLong)

#define AndroidxAnnotationColorLong AXColorLong

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxAnnotationColorLong")
