//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/annotation/annotation/src/main/java/androidx/annotation/ColorInt.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxAnnotationColorInt")
#ifdef RESTRICT_AndroidxAnnotationColorInt
#define INCLUDE_ALL_AndroidxAnnotationColorInt 0
#else
#define INCLUDE_ALL_AndroidxAnnotationColorInt 1
#endif
#undef RESTRICT_AndroidxAnnotationColorInt

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXColorInt_) && (INCLUDE_ALL_AndroidxAnnotationColorInt || defined(INCLUDE_AXColorInt))
#define AXColorInt_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol AXColorInt < JavaLangAnnotationAnnotation >

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface AXColorInt : NSObject < AXColorInt >

@end

J2OBJC_EMPTY_STATIC_INIT(AXColorInt)

FOUNDATION_EXPORT id<AXColorInt> create_AXColorInt(void);

J2OBJC_TYPE_LITERAL_HEADER(AXColorInt)

#define AndroidxAnnotationColorInt AXColorInt

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxAnnotationColorInt")
