//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/annotation/annotation/src/main/java/androidx/annotation/ContentView.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxAnnotationContentView")
#ifdef RESTRICT_AndroidxAnnotationContentView
#define INCLUDE_ALL_AndroidxAnnotationContentView 0
#else
#define INCLUDE_ALL_AndroidxAnnotationContentView 1
#endif
#undef RESTRICT_AndroidxAnnotationContentView

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXContentView_) && (INCLUDE_ALL_AndroidxAnnotationContentView || defined(INCLUDE_AXContentView))
#define AXContentView_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol AXContentView < JavaLangAnnotationAnnotation >

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface AXContentView : NSObject < AXContentView >

@end

J2OBJC_EMPTY_STATIC_INIT(AXContentView)

FOUNDATION_EXPORT id<AXContentView> create_AXContentView(void);

J2OBJC_TYPE_LITERAL_HEADER(AXContentView)

#define AndroidxAnnotationContentView AXContentView

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxAnnotationContentView")
