//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/annotation/annotation/src/main/java/androidx/annotation/DimensionUnit.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxAnnotationDimensionUnit")
#ifdef RESTRICT_AndroidxAnnotationDimensionUnit
#define INCLUDE_ALL_AndroidxAnnotationDimensionUnit 0
#else
#define INCLUDE_ALL_AndroidxAnnotationDimensionUnit 1
#endif
#undef RESTRICT_AndroidxAnnotationDimensionUnit

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXDimensionUnit_) && (INCLUDE_ALL_AndroidxAnnotationDimensionUnit || defined(INCLUDE_AXDimensionUnit))
#define AXDimensionUnit_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@protocol AXDimensionUnit < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(AXDimensionUnit)

J2OBJC_TYPE_LITERAL_HEADER(AXDimensionUnit)

#define AndroidxAnnotationDimensionUnit AXDimensionUnit

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxAnnotationDimensionUnit")
