//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/annotation/annotation/src/main/java/androidx/annotation/Dimension.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxAnnotationDimension")
#ifdef RESTRICT_AndroidxAnnotationDimension
#define INCLUDE_ALL_AndroidxAnnotationDimension 0
#else
#define INCLUDE_ALL_AndroidxAnnotationDimension 1
#endif
#undef RESTRICT_AndroidxAnnotationDimension

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXDimension_) && (INCLUDE_ALL_AndroidxAnnotationDimension || defined(INCLUDE_AXDimension))
#define AXDimension_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol AXDimension < JavaLangAnnotationAnnotation >

@property (readonly) jint unit;

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface AXDimension : NSObject < AXDimension > {
 @public
  jint unit_;
}
@property (readonly, class) jint DP NS_SWIFT_NAME(DP);
@property (readonly, class) jint PX NS_SWIFT_NAME(PX);
@property (readonly, class) jint SP NS_SWIFT_NAME(SP);

@end

J2OBJC_EMPTY_STATIC_INIT(AXDimension)

inline jint AXDimension_get_DP(void);
#define AXDimension_DP 0
J2OBJC_STATIC_FIELD_CONSTANT(AXDimension, DP, jint)

inline jint AXDimension_get_PX(void);
#define AXDimension_PX 1
J2OBJC_STATIC_FIELD_CONSTANT(AXDimension, PX, jint)

inline jint AXDimension_get_SP(void);
#define AXDimension_SP 2
J2OBJC_STATIC_FIELD_CONSTANT(AXDimension, SP, jint)

FOUNDATION_EXPORT id<AXDimension> create_AXDimension(jint unit);

J2OBJC_TYPE_LITERAL_HEADER(AXDimension)

#define AndroidxAnnotationDimension AXDimension

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxAnnotationDimension")
