//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/annotation/annotation/src/main/java/androidx/annotation/DimenRes.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxAnnotationDimenRes")
#ifdef RESTRICT_AndroidxAnnotationDimenRes
#define INCLUDE_ALL_AndroidxAnnotationDimenRes 0
#else
#define INCLUDE_ALL_AndroidxAnnotationDimenRes 1
#endif
#undef RESTRICT_AndroidxAnnotationDimenRes

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXDimenRes_) && (INCLUDE_ALL_AndroidxAnnotationDimenRes || defined(INCLUDE_AXDimenRes))
#define AXDimenRes_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol AXDimenRes < JavaLangAnnotationAnnotation >

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface AXDimenRes : NSObject < AXDimenRes >

@end

J2OBJC_EMPTY_STATIC_INIT(AXDimenRes)

FOUNDATION_EXPORT id<AXDimenRes> create_AXDimenRes(void);

J2OBJC_TYPE_LITERAL_HEADER(AXDimenRes)

#define AndroidxAnnotationDimenRes AXDimenRes

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxAnnotationDimenRes")
