//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/annotation/annotation/src/main/java/androidx/annotation/DrawableRes.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxAnnotationDrawableRes")
#ifdef RESTRICT_AndroidxAnnotationDrawableRes
#define INCLUDE_ALL_AndroidxAnnotationDrawableRes 0
#else
#define INCLUDE_ALL_AndroidxAnnotationDrawableRes 1
#endif
#undef RESTRICT_AndroidxAnnotationDrawableRes

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXDrawableRes_) && (INCLUDE_ALL_AndroidxAnnotationDrawableRes || defined(INCLUDE_AXDrawableRes))
#define AXDrawableRes_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol AXDrawableRes < JavaLangAnnotationAnnotation >

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface AXDrawableRes : NSObject < AXDrawableRes >

@end

J2OBJC_EMPTY_STATIC_INIT(AXDrawableRes)

FOUNDATION_EXPORT id<AXDrawableRes> create_AXDrawableRes(void);

J2OBJC_TYPE_LITERAL_HEADER(AXDrawableRes)

#define AndroidxAnnotationDrawableRes AXDrawableRes

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxAnnotationDrawableRes")
