//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/annotation/annotation/src/main/java/androidx/annotation/FloatRange.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxAnnotationFloatRange")
#ifdef RESTRICT_AndroidxAnnotationFloatRange
#define INCLUDE_ALL_AndroidxAnnotationFloatRange 0
#else
#define INCLUDE_ALL_AndroidxAnnotationFloatRange 1
#endif
#undef RESTRICT_AndroidxAnnotationFloatRange

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXFloatRange_) && (INCLUDE_ALL_AndroidxAnnotationFloatRange || defined(INCLUDE_AXFloatRange))
#define AXFloatRange_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol AXFloatRange < JavaLangAnnotationAnnotation >

@property (readonly) jdouble from;
@property (readonly) jdouble to;
@property (readonly) jboolean fromInclusive;
@property (readonly) jboolean toInclusive;

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface AXFloatRange : NSObject < AXFloatRange > {
 @public
  jdouble from_;
  jdouble to_;
  jboolean fromInclusive_;
  jboolean toInclusive_;
}

@end

J2OBJC_EMPTY_STATIC_INIT(AXFloatRange)

FOUNDATION_EXPORT id<AXFloatRange> create_AXFloatRange(jdouble from, jboolean fromInclusive, jdouble to, jboolean toInclusive);

J2OBJC_TYPE_LITERAL_HEADER(AXFloatRange)

#define AndroidxAnnotationFloatRange AXFloatRange

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxAnnotationFloatRange")
