//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/annotation/annotation/src/main/java/androidx/annotation/FontRes.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxAnnotationFontRes")
#ifdef RESTRICT_AndroidxAnnotationFontRes
#define INCLUDE_ALL_AndroidxAnnotationFontRes 0
#else
#define INCLUDE_ALL_AndroidxAnnotationFontRes 1
#endif
#undef RESTRICT_AndroidxAnnotationFontRes

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXFontRes_) && (INCLUDE_ALL_AndroidxAnnotationFontRes || defined(INCLUDE_AXFontRes))
#define AXFontRes_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol AXFontRes < JavaLangAnnotationAnnotation >

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface AXFontRes : NSObject < AXFontRes >

@end

J2OBJC_EMPTY_STATIC_INIT(AXFontRes)

FOUNDATION_EXPORT id<AXFontRes> create_AXFontRes(void);

J2OBJC_TYPE_LITERAL_HEADER(AXFontRes)

#define AndroidxAnnotationFontRes AXFontRes

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxAnnotationFontRes")
