//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/annotation/annotation/src/main/java/androidx/annotation/FractionRes.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxAnnotationFractionRes")
#ifdef RESTRICT_AndroidxAnnotationFractionRes
#define INCLUDE_ALL_AndroidxAnnotationFractionRes 0
#else
#define INCLUDE_ALL_AndroidxAnnotationFractionRes 1
#endif
#undef RESTRICT_AndroidxAnnotationFractionRes

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXFractionRes_) && (INCLUDE_ALL_AndroidxAnnotationFractionRes || defined(INCLUDE_AXFractionRes))
#define AXFractionRes_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol AXFractionRes < JavaLangAnnotationAnnotation >

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface AXFractionRes : NSObject < AXFractionRes >

@end

J2OBJC_EMPTY_STATIC_INIT(AXFractionRes)

FOUNDATION_EXPORT id<AXFractionRes> create_AXFractionRes(void);

J2OBJC_TYPE_LITERAL_HEADER(AXFractionRes)

#define AndroidxAnnotationFractionRes AXFractionRes

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxAnnotationFractionRes")
