//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/annotation/annotation/src/main/java/androidx/annotation/HalfFloat.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxAnnotationHalfFloat")
#ifdef RESTRICT_AndroidxAnnotationHalfFloat
#define INCLUDE_ALL_AndroidxAnnotationHalfFloat 0
#else
#define INCLUDE_ALL_AndroidxAnnotationHalfFloat 1
#endif
#undef RESTRICT_AndroidxAnnotationHalfFloat

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXHalfFloat_) && (INCLUDE_ALL_AndroidxAnnotationHalfFloat || defined(INCLUDE_AXHalfFloat))
#define AXHalfFloat_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@protocol AXHalfFloat < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(AXHalfFloat)

J2OBJC_TYPE_LITERAL_HEADER(AXHalfFloat)

#define AndroidxAnnotationHalfFloat AXHalfFloat

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxAnnotationHalfFloat")
