//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/annotation/annotation/src/main/java/androidx/annotation/IdRes.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxAnnotationIdRes")
#ifdef RESTRICT_AndroidxAnnotationIdRes
#define INCLUDE_ALL_AndroidxAnnotationIdRes 0
#else
#define INCLUDE_ALL_AndroidxAnnotationIdRes 1
#endif
#undef RESTRICT_AndroidxAnnotationIdRes

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXIdRes_) && (INCLUDE_ALL_AndroidxAnnotationIdRes || defined(INCLUDE_AXIdRes))
#define AXIdRes_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol AXIdRes < JavaLangAnnotationAnnotation >

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface AXIdRes : NSObject < AXIdRes >

@end

J2OBJC_EMPTY_STATIC_INIT(AXIdRes)

FOUNDATION_EXPORT id<AXIdRes> create_AXIdRes(void);

J2OBJC_TYPE_LITERAL_HEADER(AXIdRes)

#define AndroidxAnnotationIdRes AXIdRes

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxAnnotationIdRes")
