//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/annotation/annotation/src/main/java/androidx/annotation/InspectableProperty.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxAnnotationInspectableProperty")
#ifdef RESTRICT_AndroidxAnnotationInspectableProperty
#define INCLUDE_ALL_AndroidxAnnotationInspectableProperty 0
#else
#define INCLUDE_ALL_AndroidxAnnotationInspectableProperty 1
#endif
#undef RESTRICT_AndroidxAnnotationInspectableProperty

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXInspectableProperty_) && (INCLUDE_ALL_AndroidxAnnotationInspectableProperty || defined(INCLUDE_AXInspectableProperty))
#define AXInspectableProperty_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@protocol AXInspectableProperty < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(AXInspectableProperty)

J2OBJC_TYPE_LITERAL_HEADER(AXInspectableProperty)

#define AndroidxAnnotationInspectableProperty AXInspectableProperty

#endif

#if !defined (AXInspectableProperty_EnumEntry_) && (INCLUDE_ALL_AndroidxAnnotationInspectableProperty || defined(INCLUDE_AXInspectableProperty_EnumEntry))
#define AXInspectableProperty_EnumEntry_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@protocol AXInspectableProperty_EnumEntry < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(AXInspectableProperty_EnumEntry)

J2OBJC_TYPE_LITERAL_HEADER(AXInspectableProperty_EnumEntry)

#endif

#if !defined (AXInspectableProperty_FlagEntry_) && (INCLUDE_ALL_AndroidxAnnotationInspectableProperty || defined(INCLUDE_AXInspectableProperty_FlagEntry))
#define AXInspectableProperty_FlagEntry_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@protocol AXInspectableProperty_FlagEntry < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(AXInspectableProperty_FlagEntry)

J2OBJC_TYPE_LITERAL_HEADER(AXInspectableProperty_FlagEntry)

#endif

#if !defined (AXInspectableProperty_ValueType_) && (INCLUDE_ALL_AndroidxAnnotationInspectableProperty || defined(INCLUDE_AXInspectableProperty_ValueType))
#define AXInspectableProperty_ValueType_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

@class IOSObjectArray;

typedef NS_ENUM(NSUInteger, AXInspectableProperty_ValueType_Enum) {
  AXInspectableProperty_ValueType_Enum_NONE = 0,
  AXInspectableProperty_ValueType_Enum_INFERRED = 1,
  AXInspectableProperty_ValueType_Enum_INT_ENUM = 2,
  AXInspectableProperty_ValueType_Enum_INT_FLAG = 3,
  AXInspectableProperty_ValueType_Enum_COLOR = 4,
  AXInspectableProperty_ValueType_Enum_GRAVITY = 5,
  AXInspectableProperty_ValueType_Enum_RESOURCE_ID = 6,
};

@interface AXInspectableProperty_ValueType : JavaLangEnum

@property (readonly, class, nonnull) AXInspectableProperty_ValueType *NONE NS_SWIFT_NAME(NONE);
@property (readonly, class, nonnull) AXInspectableProperty_ValueType *INFERRED NS_SWIFT_NAME(INFERRED);
@property (readonly, class, nonnull) AXInspectableProperty_ValueType *INT_ENUM NS_SWIFT_NAME(INT_ENUM);
@property (readonly, class, nonnull) AXInspectableProperty_ValueType *INT_FLAG NS_SWIFT_NAME(INT_FLAG);
@property (readonly, class, nonnull) AXInspectableProperty_ValueType *COLOR NS_SWIFT_NAME(COLOR);
@property (readonly, class, nonnull) AXInspectableProperty_ValueType *GRAVITY NS_SWIFT_NAME(GRAVITY);
@property (readonly, class, nonnull) AXInspectableProperty_ValueType *RESOURCE_ID NS_SWIFT_NAME(RESOURCE_ID);
#pragma mark Public

+ (AXInspectableProperty_ValueType *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (AXInspectableProperty_ValueType_Enum)toNSEnum;

@end

J2OBJC_STATIC_INIT(AXInspectableProperty_ValueType)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT AXInspectableProperty_ValueType *AXInspectableProperty_ValueType_values_[];

inline AXInspectableProperty_ValueType *AXInspectableProperty_ValueType_get_NONE(void);
J2OBJC_ENUM_CONSTANT(AXInspectableProperty_ValueType, NONE)

inline AXInspectableProperty_ValueType *AXInspectableProperty_ValueType_get_INFERRED(void);
J2OBJC_ENUM_CONSTANT(AXInspectableProperty_ValueType, INFERRED)

inline AXInspectableProperty_ValueType *AXInspectableProperty_ValueType_get_INT_ENUM(void);
J2OBJC_ENUM_CONSTANT(AXInspectableProperty_ValueType, INT_ENUM)

inline AXInspectableProperty_ValueType *AXInspectableProperty_ValueType_get_INT_FLAG(void);
J2OBJC_ENUM_CONSTANT(AXInspectableProperty_ValueType, INT_FLAG)

inline AXInspectableProperty_ValueType *AXInspectableProperty_ValueType_get_COLOR(void);
J2OBJC_ENUM_CONSTANT(AXInspectableProperty_ValueType, COLOR)

inline AXInspectableProperty_ValueType *AXInspectableProperty_ValueType_get_GRAVITY(void);
J2OBJC_ENUM_CONSTANT(AXInspectableProperty_ValueType, GRAVITY)

inline AXInspectableProperty_ValueType *AXInspectableProperty_ValueType_get_RESOURCE_ID(void);
J2OBJC_ENUM_CONSTANT(AXInspectableProperty_ValueType, RESOURCE_ID)

FOUNDATION_EXPORT IOSObjectArray *AXInspectableProperty_ValueType_values(void);

FOUNDATION_EXPORT AXInspectableProperty_ValueType *AXInspectableProperty_ValueType_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT AXInspectableProperty_ValueType *AXInspectableProperty_ValueType_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(AXInspectableProperty_ValueType)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxAnnotationInspectableProperty")
