//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/annotation/annotation/src/main/java/androidx/annotation/IntDef.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxAnnotationIntDef")
#ifdef RESTRICT_AndroidxAnnotationIntDef
#define INCLUDE_ALL_AndroidxAnnotationIntDef 0
#else
#define INCLUDE_ALL_AndroidxAnnotationIntDef 1
#endif
#undef RESTRICT_AndroidxAnnotationIntDef

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXIntDef_) && (INCLUDE_ALL_AndroidxAnnotationIntDef || defined(INCLUDE_AXIntDef))
#define AXIntDef_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@protocol AXIntDef < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(AXIntDef)

J2OBJC_TYPE_LITERAL_HEADER(AXIntDef)

#define AndroidxAnnotationIntDef AXIntDef

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxAnnotationIntDef")
