//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/annotation/annotation/src/main/java/androidx/annotation/IntegerRes.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxAnnotationIntegerRes")
#ifdef RESTRICT_AndroidxAnnotationIntegerRes
#define INCLUDE_ALL_AndroidxAnnotationIntegerRes 0
#else
#define INCLUDE_ALL_AndroidxAnnotationIntegerRes 1
#endif
#undef RESTRICT_AndroidxAnnotationIntegerRes

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXIntegerRes_) && (INCLUDE_ALL_AndroidxAnnotationIntegerRes || defined(INCLUDE_AXIntegerRes))
#define AXIntegerRes_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol AXIntegerRes < JavaLangAnnotationAnnotation >

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface AXIntegerRes : NSObject < AXIntegerRes >

@end

J2OBJC_EMPTY_STATIC_INIT(AXIntegerRes)

FOUNDATION_EXPORT id<AXIntegerRes> create_AXIntegerRes(void);

J2OBJC_TYPE_LITERAL_HEADER(AXIntegerRes)

#define AndroidxAnnotationIntegerRes AXIntegerRes

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxAnnotationIntegerRes")
