//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/annotation/annotation/src/main/java/androidx/annotation/InterpolatorRes.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxAnnotationInterpolatorRes")
#ifdef RESTRICT_AndroidxAnnotationInterpolatorRes
#define INCLUDE_ALL_AndroidxAnnotationInterpolatorRes 0
#else
#define INCLUDE_ALL_AndroidxAnnotationInterpolatorRes 1
#endif
#undef RESTRICT_AndroidxAnnotationInterpolatorRes

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXInterpolatorRes_) && (INCLUDE_ALL_AndroidxAnnotationInterpolatorRes || defined(INCLUDE_AXInterpolatorRes))
#define AXInterpolatorRes_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol AXInterpolatorRes < JavaLangAnnotationAnnotation >

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface AXInterpolatorRes : NSObject < AXInterpolatorRes >

@end

J2OBJC_EMPTY_STATIC_INIT(AXInterpolatorRes)

FOUNDATION_EXPORT id<AXInterpolatorRes> create_AXInterpolatorRes(void);

J2OBJC_TYPE_LITERAL_HEADER(AXInterpolatorRes)

#define AndroidxAnnotationInterpolatorRes AXInterpolatorRes

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxAnnotationInterpolatorRes")
