//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/annotation/annotation/src/main/java/androidx/annotation/Keep.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxAnnotationKeep")
#ifdef RESTRICT_AndroidxAnnotationKeep
#define INCLUDE_ALL_AndroidxAnnotationKeep 0
#else
#define INCLUDE_ALL_AndroidxAnnotationKeep 1
#endif
#undef RESTRICT_AndroidxAnnotationKeep

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXKeep_) && (INCLUDE_ALL_AndroidxAnnotationKeep || defined(INCLUDE_AXKeep))
#define AXKeep_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol AXKeep < JavaLangAnnotationAnnotation >

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface AXKeep : NSObject < AXKeep >

@end

J2OBJC_EMPTY_STATIC_INIT(AXKeep)

FOUNDATION_EXPORT id<AXKeep> create_AXKeep(void);

J2OBJC_TYPE_LITERAL_HEADER(AXKeep)

#define AndroidxAnnotationKeep AXKeep

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxAnnotationKeep")
