//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/annotation/annotation/src/main/java/androidx/annotation/LayoutRes.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxAnnotationLayoutRes")
#ifdef RESTRICT_AndroidxAnnotationLayoutRes
#define INCLUDE_ALL_AndroidxAnnotationLayoutRes 0
#else
#define INCLUDE_ALL_AndroidxAnnotationLayoutRes 1
#endif
#undef RESTRICT_AndroidxAnnotationLayoutRes

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXLayoutRes_) && (INCLUDE_ALL_AndroidxAnnotationLayoutRes || defined(INCLUDE_AXLayoutRes))
#define AXLayoutRes_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol AXLayoutRes < JavaLangAnnotationAnnotation >

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface AXLayoutRes : NSObject < AXLayoutRes >

@end

J2OBJC_EMPTY_STATIC_INIT(AXLayoutRes)

FOUNDATION_EXPORT id<AXLayoutRes> create_AXLayoutRes(void);

J2OBJC_TYPE_LITERAL_HEADER(AXLayoutRes)

#define AndroidxAnnotationLayoutRes AXLayoutRes

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxAnnotationLayoutRes")
