//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/annotation/annotation/src/main/java/androidx/annotation/MainThread.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxAnnotationMainThread")
#ifdef RESTRICT_AndroidxAnnotationMainThread
#define INCLUDE_ALL_AndroidxAnnotationMainThread 0
#else
#define INCLUDE_ALL_AndroidxAnnotationMainThread 1
#endif
#undef RESTRICT_AndroidxAnnotationMainThread

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXMainThread_) && (INCLUDE_ALL_AndroidxAnnotationMainThread || defined(INCLUDE_AXMainThread))
#define AXMainThread_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol AXMainThread < JavaLangAnnotationAnnotation >

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface AXMainThread : NSObject < AXMainThread >

@end

J2OBJC_EMPTY_STATIC_INIT(AXMainThread)

FOUNDATION_EXPORT id<AXMainThread> create_AXMainThread(void);

J2OBJC_TYPE_LITERAL_HEADER(AXMainThread)

#define AndroidxAnnotationMainThread AXMainThread

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxAnnotationMainThread")
