//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/annotation/annotation/src/main/java/androidx/annotation/NonNull.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxAnnotationNonNull")
#ifdef RESTRICT_AndroidxAnnotationNonNull
#define INCLUDE_ALL_AndroidxAnnotationNonNull 0
#else
#define INCLUDE_ALL_AndroidxAnnotationNonNull 1
#endif
#undef RESTRICT_AndroidxAnnotationNonNull

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXNonNull_) && (INCLUDE_ALL_AndroidxAnnotationNonNull || defined(INCLUDE_AXNonNull))
#define AXNonNull_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol AXNonNull < JavaLangAnnotationAnnotation >

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface AXNonNull : NSObject < AXNonNull >

@end

J2OBJC_EMPTY_STATIC_INIT(AXNonNull)

FOUNDATION_EXPORT id<AXNonNull> create_AXNonNull(void);

J2OBJC_TYPE_LITERAL_HEADER(AXNonNull)

#define AndroidxAnnotationNonNull AXNonNull

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxAnnotationNonNull")
