//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/annotation/annotation/src/main/java/androidx/annotation/PluralsRes.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxAnnotationPluralsRes")
#ifdef RESTRICT_AndroidxAnnotationPluralsRes
#define INCLUDE_ALL_AndroidxAnnotationPluralsRes 0
#else
#define INCLUDE_ALL_AndroidxAnnotationPluralsRes 1
#endif
#undef RESTRICT_AndroidxAnnotationPluralsRes

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXPluralsRes_) && (INCLUDE_ALL_AndroidxAnnotationPluralsRes || defined(INCLUDE_AXPluralsRes))
#define AXPluralsRes_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol AXPluralsRes < JavaLangAnnotationAnnotation >

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface AXPluralsRes : NSObject < AXPluralsRes >

@end

J2OBJC_EMPTY_STATIC_INIT(AXPluralsRes)

FOUNDATION_EXPORT id<AXPluralsRes> create_AXPluralsRes(void);

J2OBJC_TYPE_LITERAL_HEADER(AXPluralsRes)

#define AndroidxAnnotationPluralsRes AXPluralsRes

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxAnnotationPluralsRes")
