//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/annotation/annotation/src/main/java/androidx/annotation/ProductionVisibility.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxAnnotationProductionVisibility")
#ifdef RESTRICT_AndroidxAnnotationProductionVisibility
#define INCLUDE_ALL_AndroidxAnnotationProductionVisibility 0
#else
#define INCLUDE_ALL_AndroidxAnnotationProductionVisibility 1
#endif
#undef RESTRICT_AndroidxAnnotationProductionVisibility

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXProductionVisibility_) && (INCLUDE_ALL_AndroidxAnnotationProductionVisibility || defined(INCLUDE_AXProductionVisibility))
#define AXProductionVisibility_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@protocol AXProductionVisibility < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(AXProductionVisibility)

J2OBJC_TYPE_LITERAL_HEADER(AXProductionVisibility)

#define AndroidxAnnotationProductionVisibility AXProductionVisibility

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxAnnotationProductionVisibility")
