//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/annotation/annotation/src/main/java/androidx/annotation/Px.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxAnnotationPx")
#ifdef RESTRICT_AndroidxAnnotationPx
#define INCLUDE_ALL_AndroidxAnnotationPx 0
#else
#define INCLUDE_ALL_AndroidxAnnotationPx 1
#endif
#undef RESTRICT_AndroidxAnnotationPx

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXPx_) && (INCLUDE_ALL_AndroidxAnnotationPx || defined(INCLUDE_AXPx))
#define AXPx_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol AXPx < JavaLangAnnotationAnnotation >

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface AXPx : NSObject < AXPx >

@end

J2OBJC_EMPTY_STATIC_INIT(AXPx)

FOUNDATION_EXPORT id<AXPx> create_AXPx(void);

J2OBJC_TYPE_LITERAL_HEADER(AXPx)

#define AndroidxAnnotationPx AXPx

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxAnnotationPx")
