//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/annotation/annotation/src/main/java/androidx/annotation/RawRes.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxAnnotationRawRes")
#ifdef RESTRICT_AndroidxAnnotationRawRes
#define INCLUDE_ALL_AndroidxAnnotationRawRes 0
#else
#define INCLUDE_ALL_AndroidxAnnotationRawRes 1
#endif
#undef RESTRICT_AndroidxAnnotationRawRes

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXRawRes_) && (INCLUDE_ALL_AndroidxAnnotationRawRes || defined(INCLUDE_AXRawRes))
#define AXRawRes_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol AXRawRes < JavaLangAnnotationAnnotation >

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface AXRawRes : NSObject < AXRawRes >

@end

J2OBJC_EMPTY_STATIC_INIT(AXRawRes)

FOUNDATION_EXPORT id<AXRawRes> create_AXRawRes(void);

J2OBJC_TYPE_LITERAL_HEADER(AXRawRes)

#define AndroidxAnnotationRawRes AXRawRes

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxAnnotationRawRes")
