//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/annotation/annotation/src/main/java/androidx/annotation/RequiresFeature.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxAnnotationRequiresFeature")
#ifdef RESTRICT_AndroidxAnnotationRequiresFeature
#define INCLUDE_ALL_AndroidxAnnotationRequiresFeature 0
#else
#define INCLUDE_ALL_AndroidxAnnotationRequiresFeature 1
#endif
#undef RESTRICT_AndroidxAnnotationRequiresFeature

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXRequiresFeature_) && (INCLUDE_ALL_AndroidxAnnotationRequiresFeature || defined(INCLUDE_AXRequiresFeature))
#define AXRequiresFeature_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@protocol AXRequiresFeature < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(AXRequiresFeature)

J2OBJC_TYPE_LITERAL_HEADER(AXRequiresFeature)

#define AndroidxAnnotationRequiresFeature AXRequiresFeature

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxAnnotationRequiresFeature")
