//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/annotation/annotation/src/main/java/androidx/annotation/StringDef.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxAnnotationStringDef")
#ifdef RESTRICT_AndroidxAnnotationStringDef
#define INCLUDE_ALL_AndroidxAnnotationStringDef 0
#else
#define INCLUDE_ALL_AndroidxAnnotationStringDef 1
#endif
#undef RESTRICT_AndroidxAnnotationStringDef

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXStringDef_) && (INCLUDE_ALL_AndroidxAnnotationStringDef || defined(INCLUDE_AXStringDef))
#define AXStringDef_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@protocol AXStringDef < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(AXStringDef)

J2OBJC_TYPE_LITERAL_HEADER(AXStringDef)

#define AndroidxAnnotationStringDef AXStringDef

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxAnnotationStringDef")
