//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/annotation/annotation/src/main/java/androidx/annotation/StyleableRes.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxAnnotationStyleableRes")
#ifdef RESTRICT_AndroidxAnnotationStyleableRes
#define INCLUDE_ALL_AndroidxAnnotationStyleableRes 0
#else
#define INCLUDE_ALL_AndroidxAnnotationStyleableRes 1
#endif
#undef RESTRICT_AndroidxAnnotationStyleableRes

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXStyleableRes_) && (INCLUDE_ALL_AndroidxAnnotationStyleableRes || defined(INCLUDE_AXStyleableRes))
#define AXStyleableRes_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol AXStyleableRes < JavaLangAnnotationAnnotation >

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface AXStyleableRes : NSObject < AXStyleableRes >

@end

J2OBJC_EMPTY_STATIC_INIT(AXStyleableRes)

FOUNDATION_EXPORT id<AXStyleableRes> create_AXStyleableRes(void);

J2OBJC_TYPE_LITERAL_HEADER(AXStyleableRes)

#define AndroidxAnnotationStyleableRes AXStyleableRes

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxAnnotationStyleableRes")
