//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/annotation/annotation/src/main/java/androidx/annotation/TransitionRes.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxAnnotationTransitionRes")
#ifdef RESTRICT_AndroidxAnnotationTransitionRes
#define INCLUDE_ALL_AndroidxAnnotationTransitionRes 0
#else
#define INCLUDE_ALL_AndroidxAnnotationTransitionRes 1
#endif
#undef RESTRICT_AndroidxAnnotationTransitionRes

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXTransitionRes_) && (INCLUDE_ALL_AndroidxAnnotationTransitionRes || defined(INCLUDE_AXTransitionRes))
#define AXTransitionRes_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@protocol AXTransitionRes < JavaLangAnnotationAnnotation >

@end

J2OBJC_EMPTY_STATIC_INIT(AXTransitionRes)

J2OBJC_TYPE_LITERAL_HEADER(AXTransitionRes)

#define AndroidxAnnotationTransitionRes AXTransitionRes

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxAnnotationTransitionRes")
