//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/annotation/annotation/src/main/java/androidx/annotation/UiThread.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxAnnotationUiThread")
#ifdef RESTRICT_AndroidxAnnotationUiThread
#define INCLUDE_ALL_AndroidxAnnotationUiThread 0
#else
#define INCLUDE_ALL_AndroidxAnnotationUiThread 1
#endif
#undef RESTRICT_AndroidxAnnotationUiThread

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXUiThread_) && (INCLUDE_ALL_AndroidxAnnotationUiThread || defined(INCLUDE_AXUiThread))
#define AXUiThread_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;

@protocol AXUiThread < JavaLangAnnotationAnnotation >

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface AXUiThread : NSObject < AXUiThread >

@end

J2OBJC_EMPTY_STATIC_INIT(AXUiThread)

FOUNDATION_EXPORT id<AXUiThread> create_AXUiThread(void);

J2OBJC_TYPE_LITERAL_HEADER(AXUiThread)

#define AndroidxAnnotationUiThread AXUiThread

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxAnnotationUiThread")
