//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/lifecycle/lifecycle-common/src/main/java/androidx/lifecycle/CompositeGeneratedAdaptersObserver.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxLifecycleCompositeGeneratedAdaptersObserver")
#ifdef RESTRICT_AndroidxLifecycleCompositeGeneratedAdaptersObserver
#define INCLUDE_ALL_AndroidxLifecycleCompositeGeneratedAdaptersObserver 0
#else
#define INCLUDE_ALL_AndroidxLifecycleCompositeGeneratedAdaptersObserver 1
#endif
#undef RESTRICT_AndroidxLifecycleCompositeGeneratedAdaptersObserver

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXCompositeGeneratedAdaptersObserver_) && (INCLUDE_ALL_AndroidxLifecycleCompositeGeneratedAdaptersObserver || defined(INCLUDE_AXCompositeGeneratedAdaptersObserver))
#define AXCompositeGeneratedAdaptersObserver_

#define RESTRICT_AndroidxLifecycleLifecycleEventObserver 1
#define INCLUDE_AXLifecycleEventObserver 1
#include "androidx/lifecycle/LifecycleEventObserver.h"

@class AXLifecycle_Event;
@class IOSObjectArray;
@protocol AXLifecycleOwner;

@interface AXCompositeGeneratedAdaptersObserver : NSObject < AXLifecycleEventObserver >

#pragma mark Public

- (void)onStateChangedWithAXLifecycleOwner:(id<AXLifecycleOwner> __nonnull)source
                     withAXLifecycle_Event:(AXLifecycle_Event * __nonnull)event;

#pragma mark Package-Private

- (instancetype __nonnull)initPackagePrivateWithAXGeneratedAdapterArray:(IOSObjectArray *)generatedAdapters;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(AXCompositeGeneratedAdaptersObserver)

FOUNDATION_EXPORT void AXCompositeGeneratedAdaptersObserver_initPackagePrivateWithAXGeneratedAdapterArray_(AXCompositeGeneratedAdaptersObserver *self, IOSObjectArray *generatedAdapters);

FOUNDATION_EXPORT AXCompositeGeneratedAdaptersObserver *new_AXCompositeGeneratedAdaptersObserver_initPackagePrivateWithAXGeneratedAdapterArray_(IOSObjectArray *generatedAdapters) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AXCompositeGeneratedAdaptersObserver *create_AXCompositeGeneratedAdaptersObserver_initPackagePrivateWithAXGeneratedAdapterArray_(IOSObjectArray *generatedAdapters);

J2OBJC_TYPE_LITERAL_HEADER(AXCompositeGeneratedAdaptersObserver)

@compatibility_alias AndroidxLifecycleCompositeGeneratedAdaptersObserver AXCompositeGeneratedAdaptersObserver;

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxLifecycleCompositeGeneratedAdaptersObserver")
