//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/lifecycle/lifecycle-common/src/main/java/androidx/lifecycle/FullLifecycleObserver.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxLifecycleFullLifecycleObserver")
#ifdef RESTRICT_AndroidxLifecycleFullLifecycleObserver
#define INCLUDE_ALL_AndroidxLifecycleFullLifecycleObserver 0
#else
#define INCLUDE_ALL_AndroidxLifecycleFullLifecycleObserver 1
#endif
#undef RESTRICT_AndroidxLifecycleFullLifecycleObserver

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXFullLifecycleObserver_) && (INCLUDE_ALL_AndroidxLifecycleFullLifecycleObserver || defined(INCLUDE_AXFullLifecycleObserver))
#define AXFullLifecycleObserver_

#define RESTRICT_AndroidxLifecycleLifecycleObserver 1
#define INCLUDE_AXLifecycleObserver 1
#include "androidx/lifecycle/LifecycleObserver.h"

@protocol AXLifecycleOwner;

@protocol AXFullLifecycleObserver < AXLifecycleObserver, JavaObject >

- (void)onCreateWithAXLifecycleOwner:(id<AXLifecycleOwner>)owner;

- (void)onStartWithAXLifecycleOwner:(id<AXLifecycleOwner>)owner;

- (void)onResumeWithAXLifecycleOwner:(id<AXLifecycleOwner>)owner;

- (void)onPauseWithAXLifecycleOwner:(id<AXLifecycleOwner>)owner;

- (void)onStopWithAXLifecycleOwner:(id<AXLifecycleOwner>)owner;

- (void)onDestroyWithAXLifecycleOwner:(id<AXLifecycleOwner>)owner;

@end

J2OBJC_EMPTY_STATIC_INIT(AXFullLifecycleObserver)

J2OBJC_TYPE_LITERAL_HEADER(AXFullLifecycleObserver)

#define AndroidxLifecycleFullLifecycleObserver AXFullLifecycleObserver

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxLifecycleFullLifecycleObserver")
