//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/lifecycle/lifecycle-common/src/main/java/androidx/lifecycle/GeneratedAdapter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxLifecycleGeneratedAdapter")
#ifdef RESTRICT_AndroidxLifecycleGeneratedAdapter
#define INCLUDE_ALL_AndroidxLifecycleGeneratedAdapter 0
#else
#define INCLUDE_ALL_AndroidxLifecycleGeneratedAdapter 1
#endif
#undef RESTRICT_AndroidxLifecycleGeneratedAdapter

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXGeneratedAdapter_) && (INCLUDE_ALL_AndroidxLifecycleGeneratedAdapter || defined(INCLUDE_AXGeneratedAdapter))
#define AXGeneratedAdapter_

@class AXLifecycle_Event;
@class AXMethodCallsLogger;
@protocol AXLifecycleOwner;

@protocol AXGeneratedAdapter < JavaObject >

- (void)callMethodsWithAXLifecycleOwner:(id<AXLifecycleOwner>)source
                  withAXLifecycle_Event:(AXLifecycle_Event *)event
                            withBoolean:(jboolean)onAny
                withAXMethodCallsLogger:(AXMethodCallsLogger *)logger;

@end

J2OBJC_EMPTY_STATIC_INIT(AXGeneratedAdapter)

J2OBJC_TYPE_LITERAL_HEADER(AXGeneratedAdapter)

#define AndroidxLifecycleGeneratedAdapter AXGeneratedAdapter

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxLifecycleGeneratedAdapter")
