//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/lifecycle/lifecycle-common/src/main/java/androidx/lifecycle/GenericLifecycleObserver.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxLifecycleGenericLifecycleObserver")
#ifdef RESTRICT_AndroidxLifecycleGenericLifecycleObserver
#define INCLUDE_ALL_AndroidxLifecycleGenericLifecycleObserver 0
#else
#define INCLUDE_ALL_AndroidxLifecycleGenericLifecycleObserver 1
#endif
#undef RESTRICT_AndroidxLifecycleGenericLifecycleObserver

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXGenericLifecycleObserver_) && (INCLUDE_ALL_AndroidxLifecycleGenericLifecycleObserver || defined(INCLUDE_AXGenericLifecycleObserver))
#define AXGenericLifecycleObserver_

#define RESTRICT_AndroidxLifecycleLifecycleEventObserver 1
#define INCLUDE_AXLifecycleEventObserver 1
#include "androidx/lifecycle/LifecycleEventObserver.h"

@protocol AXGenericLifecycleObserver < AXLifecycleEventObserver, JavaObject >

@end

J2OBJC_EMPTY_STATIC_INIT(AXGenericLifecycleObserver)

J2OBJC_TYPE_LITERAL_HEADER(AXGenericLifecycleObserver)

#define AndroidxLifecycleGenericLifecycleObserver AXGenericLifecycleObserver

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxLifecycleGenericLifecycleObserver")
