//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/lifecycle/lifecycle-common/src/main/java/androidx/lifecycle/LifecycleObserver.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxLifecycleLifecycleObserver")
#ifdef RESTRICT_AndroidxLifecycleLifecycleObserver
#define INCLUDE_ALL_AndroidxLifecycleLifecycleObserver 0
#else
#define INCLUDE_ALL_AndroidxLifecycleLifecycleObserver 1
#endif
#undef RESTRICT_AndroidxLifecycleLifecycleObserver

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXLifecycleObserver_) && (INCLUDE_ALL_AndroidxLifecycleLifecycleObserver || defined(INCLUDE_AXLifecycleObserver))
#define AXLifecycleObserver_

@protocol AXLifecycleObserver < JavaObject >

@end

J2OBJC_EMPTY_STATIC_INIT(AXLifecycleObserver)

J2OBJC_TYPE_LITERAL_HEADER(AXLifecycleObserver)

#define AndroidxLifecycleLifecycleObserver AXLifecycleObserver

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxLifecycleLifecycleObserver")
