//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/lifecycle/lifecycle-common/src/main/java/androidx/lifecycle/LifecycleEventObserver.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxLifecycleLifecycleEventObserver")
#ifdef RESTRICT_AndroidxLifecycleLifecycleEventObserver
#define INCLUDE_ALL_AndroidxLifecycleLifecycleEventObserver 0
#else
#define INCLUDE_ALL_AndroidxLifecycleLifecycleEventObserver 1
#endif
#undef RESTRICT_AndroidxLifecycleLifecycleEventObserver

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXLifecycleEventObserver_) && (INCLUDE_ALL_AndroidxLifecycleLifecycleEventObserver || defined(INCLUDE_AXLifecycleEventObserver))
#define AXLifecycleEventObserver_

#define RESTRICT_AndroidxLifecycleLifecycleObserver 1
#define INCLUDE_AXLifecycleObserver 1
#include "androidx/lifecycle/LifecycleObserver.h"

@class AXLifecycle_Event;
@protocol AXLifecycleOwner;

@protocol AXLifecycleEventObserver < AXLifecycleObserver, JavaObject >

- (void)onStateChangedWithAXLifecycleOwner:(id<AXLifecycleOwner> __nonnull)source
                     withAXLifecycle_Event:(AXLifecycle_Event * __nonnull)event;

@end

J2OBJC_EMPTY_STATIC_INIT(AXLifecycleEventObserver)

J2OBJC_TYPE_LITERAL_HEADER(AXLifecycleEventObserver)

#define AndroidxLifecycleLifecycleEventObserver AXLifecycleEventObserver

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxLifecycleLifecycleEventObserver")
