//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/lifecycle/lifecycle-common/src/main/java/androidx/lifecycle/LifecycleOwner.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxLifecycleLifecycleOwner")
#ifdef RESTRICT_AndroidxLifecycleLifecycleOwner
#define INCLUDE_ALL_AndroidxLifecycleLifecycleOwner 0
#else
#define INCLUDE_ALL_AndroidxLifecycleLifecycleOwner 1
#endif
#undef RESTRICT_AndroidxLifecycleLifecycleOwner

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXLifecycleOwner_) && (INCLUDE_ALL_AndroidxLifecycleLifecycleOwner || defined(INCLUDE_AXLifecycleOwner))
#define AXLifecycleOwner_

@class AXLifecycle;

@protocol AXLifecycleOwner < JavaObject >

- (AXLifecycle * __nonnull)getLifecycle;

@end

J2OBJC_EMPTY_STATIC_INIT(AXLifecycleOwner)

J2OBJC_TYPE_LITERAL_HEADER(AXLifecycleOwner)

#define AndroidxLifecycleLifecycleOwner AXLifecycleOwner

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxLifecycleLifecycleOwner")
