//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/lifecycle/lifecycle-common/src/main/java/androidx/lifecycle/Lifecycle.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxLifecycleLifecycle")
#ifdef RESTRICT_AndroidxLifecycleLifecycle
#define INCLUDE_ALL_AndroidxLifecycleLifecycle 0
#else
#define INCLUDE_ALL_AndroidxLifecycleLifecycle 1
#endif
#undef RESTRICT_AndroidxLifecycleLifecycle

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXLifecycle_) && (INCLUDE_ALL_AndroidxLifecycleLifecycle || defined(INCLUDE_AXLifecycle))
#define AXLifecycle_

@class AXLifecycle_State;
@class JavaUtilConcurrentAtomicAtomicReference;
@protocol AXLifecycleObserver;

@interface AXLifecycle : NSObject {
 @public
  JavaUtilConcurrentAtomicAtomicReference *mInternalScopeRef_;
}

#pragma mark Public

- (instancetype __nonnull)init;

- (void)addObserverWithAXLifecycleObserver:(id<AXLifecycleObserver> __nonnull)observer;

- (AXLifecycle_State * __nonnull)getCurrentState;

- (void)removeObserverWithAXLifecycleObserver:(id<AXLifecycleObserver> __nonnull)observer;

@end

J2OBJC_EMPTY_STATIC_INIT(AXLifecycle)

J2OBJC_FIELD_SETTER(AXLifecycle, mInternalScopeRef_, JavaUtilConcurrentAtomicAtomicReference *)

FOUNDATION_EXPORT void AXLifecycle_init(AXLifecycle *self);

J2OBJC_TYPE_LITERAL_HEADER(AXLifecycle)

@compatibility_alias AndroidxLifecycleLifecycle AXLifecycle;

#endif

#if !defined (AXLifecycle_Event_) && (INCLUDE_ALL_AndroidxLifecycleLifecycle || defined(INCLUDE_AXLifecycle_Event))
#define AXLifecycle_Event_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

@class AXLifecycle_State;
@class IOSObjectArray;

typedef NS_ENUM(NSUInteger, AXLifecycle_Event_Enum) {
  AXLifecycle_Event_Enum_ON_CREATE = 0,
  AXLifecycle_Event_Enum_ON_START = 1,
  AXLifecycle_Event_Enum_ON_RESUME = 2,
  AXLifecycle_Event_Enum_ON_PAUSE = 3,
  AXLifecycle_Event_Enum_ON_STOP = 4,
  AXLifecycle_Event_Enum_ON_DESTROY = 5,
  AXLifecycle_Event_Enum_ON_ANY = 6,
};

@interface AXLifecycle_Event : JavaLangEnum

@property (readonly, class, nonnull) AXLifecycle_Event *ON_CREATE NS_SWIFT_NAME(ON_CREATE);
@property (readonly, class, nonnull) AXLifecycle_Event *ON_START NS_SWIFT_NAME(ON_START);
@property (readonly, class, nonnull) AXLifecycle_Event *ON_RESUME NS_SWIFT_NAME(ON_RESUME);
@property (readonly, class, nonnull) AXLifecycle_Event *ON_PAUSE NS_SWIFT_NAME(ON_PAUSE);
@property (readonly, class, nonnull) AXLifecycle_Event *ON_STOP NS_SWIFT_NAME(ON_STOP);
@property (readonly, class, nonnull) AXLifecycle_Event *ON_DESTROY NS_SWIFT_NAME(ON_DESTROY);
@property (readonly, class, nonnull) AXLifecycle_Event *ON_ANY NS_SWIFT_NAME(ON_ANY);
#pragma mark Public

+ (AXLifecycle_Event * __nullable)downFromWithAXLifecycle_State:(AXLifecycle_State * __nonnull)state;

+ (AXLifecycle_Event * __nullable)downToWithAXLifecycle_State:(AXLifecycle_State * __nonnull)state;

- (AXLifecycle_State * __nonnull)getTargetState;

+ (AXLifecycle_Event * __nullable)upFromWithAXLifecycle_State:(AXLifecycle_State * __nonnull)state;

+ (AXLifecycle_Event * __nullable)upToWithAXLifecycle_State:(AXLifecycle_State * __nonnull)state;

+ (AXLifecycle_Event *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (AXLifecycle_Event_Enum)toNSEnum;

@end

J2OBJC_STATIC_INIT(AXLifecycle_Event)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT AXLifecycle_Event *AXLifecycle_Event_values_[];

inline AXLifecycle_Event *AXLifecycle_Event_get_ON_CREATE(void);
J2OBJC_ENUM_CONSTANT(AXLifecycle_Event, ON_CREATE)

inline AXLifecycle_Event *AXLifecycle_Event_get_ON_START(void);
J2OBJC_ENUM_CONSTANT(AXLifecycle_Event, ON_START)

inline AXLifecycle_Event *AXLifecycle_Event_get_ON_RESUME(void);
J2OBJC_ENUM_CONSTANT(AXLifecycle_Event, ON_RESUME)

inline AXLifecycle_Event *AXLifecycle_Event_get_ON_PAUSE(void);
J2OBJC_ENUM_CONSTANT(AXLifecycle_Event, ON_PAUSE)

inline AXLifecycle_Event *AXLifecycle_Event_get_ON_STOP(void);
J2OBJC_ENUM_CONSTANT(AXLifecycle_Event, ON_STOP)

inline AXLifecycle_Event *AXLifecycle_Event_get_ON_DESTROY(void);
J2OBJC_ENUM_CONSTANT(AXLifecycle_Event, ON_DESTROY)

inline AXLifecycle_Event *AXLifecycle_Event_get_ON_ANY(void);
J2OBJC_ENUM_CONSTANT(AXLifecycle_Event, ON_ANY)

FOUNDATION_EXPORT AXLifecycle_Event *AXLifecycle_Event_downFromWithAXLifecycle_State_(AXLifecycle_State *state);

FOUNDATION_EXPORT AXLifecycle_Event *AXLifecycle_Event_downToWithAXLifecycle_State_(AXLifecycle_State *state);

FOUNDATION_EXPORT AXLifecycle_Event *AXLifecycle_Event_upFromWithAXLifecycle_State_(AXLifecycle_State *state);

FOUNDATION_EXPORT AXLifecycle_Event *AXLifecycle_Event_upToWithAXLifecycle_State_(AXLifecycle_State *state);

FOUNDATION_EXPORT IOSObjectArray *AXLifecycle_Event_values(void);

FOUNDATION_EXPORT AXLifecycle_Event *AXLifecycle_Event_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT AXLifecycle_Event *AXLifecycle_Event_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(AXLifecycle_Event)

#endif

#if !defined (AXLifecycle_State_) && (INCLUDE_ALL_AndroidxLifecycleLifecycle || defined(INCLUDE_AXLifecycle_State))
#define AXLifecycle_State_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

@class IOSObjectArray;

typedef NS_ENUM(NSUInteger, AXLifecycle_State_Enum) {
  AXLifecycle_State_Enum_DESTROYED = 0,
  AXLifecycle_State_Enum_INITIALIZED = 1,
  AXLifecycle_State_Enum_CREATED = 2,
  AXLifecycle_State_Enum_STARTED = 3,
  AXLifecycle_State_Enum_RESUMED = 4,
};

@interface AXLifecycle_State : JavaLangEnum

@property (readonly, class, nonnull) AXLifecycle_State *DESTROYED NS_SWIFT_NAME(DESTROYED);
@property (readonly, class, nonnull) AXLifecycle_State *INITIALIZED NS_SWIFT_NAME(INITIALIZED);
@property (readonly, class, nonnull) AXLifecycle_State *CREATED NS_SWIFT_NAME(CREATED);
@property (readonly, class, nonnull) AXLifecycle_State *STARTED NS_SWIFT_NAME(STARTED);
@property (readonly, class, nonnull) AXLifecycle_State *RESUMED NS_SWIFT_NAME(RESUMED);
#pragma mark Public

- (jboolean)isAtLeastWithAXLifecycle_State:(AXLifecycle_State * __nonnull)state;

+ (AXLifecycle_State *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (AXLifecycle_State_Enum)toNSEnum;

@end

J2OBJC_STATIC_INIT(AXLifecycle_State)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT AXLifecycle_State *AXLifecycle_State_values_[];

inline AXLifecycle_State *AXLifecycle_State_get_DESTROYED(void);
J2OBJC_ENUM_CONSTANT(AXLifecycle_State, DESTROYED)

inline AXLifecycle_State *AXLifecycle_State_get_INITIALIZED(void);
J2OBJC_ENUM_CONSTANT(AXLifecycle_State, INITIALIZED)

inline AXLifecycle_State *AXLifecycle_State_get_CREATED(void);
J2OBJC_ENUM_CONSTANT(AXLifecycle_State, CREATED)

inline AXLifecycle_State *AXLifecycle_State_get_STARTED(void);
J2OBJC_ENUM_CONSTANT(AXLifecycle_State, STARTED)

inline AXLifecycle_State *AXLifecycle_State_get_RESUMED(void);
J2OBJC_ENUM_CONSTANT(AXLifecycle_State, RESUMED)

FOUNDATION_EXPORT IOSObjectArray *AXLifecycle_State_values(void);

FOUNDATION_EXPORT AXLifecycle_State *AXLifecycle_State_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT AXLifecycle_State *AXLifecycle_State_fromOrdinal(NSUInteger ordinal);

J2OBJC_TYPE_LITERAL_HEADER(AXLifecycle_State)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxLifecycleLifecycle")
