//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/lifecycle/lifecycle-common/src/main/java/androidx/lifecycle/Lifecycling.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxLifecycleLifecycling")
#ifdef RESTRICT_AndroidxLifecycleLifecycling
#define INCLUDE_ALL_AndroidxLifecycleLifecycling 0
#else
#define INCLUDE_ALL_AndroidxLifecycleLifecycling 1
#endif
#undef RESTRICT_AndroidxLifecycleLifecycling

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXLifecycling_) && (INCLUDE_ALL_AndroidxLifecycleLifecycling || defined(INCLUDE_AXLifecycling))
#define AXLifecycling_

@protocol AXGenericLifecycleObserver;
@protocol AXLifecycleEventObserver;

@interface AXLifecycling : NSObject

#pragma mark Public

+ (NSString *)getAdapterNameWithNSString:(NSString *)className_;

#pragma mark Package-Private

+ (id<AXGenericLifecycleObserver> __nonnull)getCallbackWithId:(id)object;

+ (id<AXLifecycleEventObserver> __nonnull)lifecycleEventObserverWithId:(id)object;

@end

J2OBJC_STATIC_INIT(AXLifecycling)

FOUNDATION_EXPORT id<AXGenericLifecycleObserver> AXLifecycling_getCallbackWithId_(id object);

FOUNDATION_EXPORT id<AXLifecycleEventObserver> AXLifecycling_lifecycleEventObserverWithId_(id object);

FOUNDATION_EXPORT NSString *AXLifecycling_getAdapterNameWithNSString_(NSString *className_);

J2OBJC_TYPE_LITERAL_HEADER(AXLifecycling)

@compatibility_alias AndroidxLifecycleLifecycling AXLifecycling;

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxLifecycleLifecycling")
