//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/lifecycle/lifecycle-livedata/src/main/java/androidx/lifecycle/MediatorLiveData.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxLifecycleMediatorLiveData")
#ifdef RESTRICT_AndroidxLifecycleMediatorLiveData
#define INCLUDE_ALL_AndroidxLifecycleMediatorLiveData 0
#else
#define INCLUDE_ALL_AndroidxLifecycleMediatorLiveData 1
#endif
#undef RESTRICT_AndroidxLifecycleMediatorLiveData

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXMediatorLiveData_) && (INCLUDE_ALL_AndroidxLifecycleMediatorLiveData || defined(INCLUDE_AXMediatorLiveData))
#define AXMediatorLiveData_

#define RESTRICT_AndroidxLifecycleMutableLiveData 1
#define INCLUDE_AXMutableLiveData 1
#include "androidx/lifecycle/MutableLiveData.h"

@class AXLiveData;
@protocol AXObserver;

@interface AXMediatorLiveData : AXMutableLiveData

#pragma mark Public

- (instancetype __nonnull)init;

- (void)addSourceWithAXLiveData:(AXLiveData * __nonnull)source
                 withAXObserver:(id<AXObserver> __nonnull)onChanged;

- (void)removeSourceWithAXLiveData:(AXLiveData * __nonnull)toRemote;

#pragma mark Protected

- (void)onActive;

- (void)onInactive;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)initWithId:(id)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(AXMediatorLiveData)

FOUNDATION_EXPORT void AXMediatorLiveData_init(AXMediatorLiveData *self);

FOUNDATION_EXPORT AXMediatorLiveData *new_AXMediatorLiveData_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AXMediatorLiveData *create_AXMediatorLiveData_init(void);

J2OBJC_TYPE_LITERAL_HEADER(AXMediatorLiveData)

@compatibility_alias AndroidxLifecycleMediatorLiveData AXMediatorLiveData;

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxLifecycleMediatorLiveData")
