//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/lifecycle/lifecycle-common/src/main/java/androidx/lifecycle/MethodCallsLogger.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxLifecycleMethodCallsLogger")
#ifdef RESTRICT_AndroidxLifecycleMethodCallsLogger
#define INCLUDE_ALL_AndroidxLifecycleMethodCallsLogger 0
#else
#define INCLUDE_ALL_AndroidxLifecycleMethodCallsLogger 1
#endif
#undef RESTRICT_AndroidxLifecycleMethodCallsLogger

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXMethodCallsLogger_) && (INCLUDE_ALL_AndroidxLifecycleMethodCallsLogger || defined(INCLUDE_AXMethodCallsLogger))
#define AXMethodCallsLogger_

@interface AXMethodCallsLogger : NSObject

#pragma mark Public

- (instancetype __nonnull)init;

- (jboolean)approveCallWithNSString:(NSString *)name
                            withInt:(jint)type;

@end

J2OBJC_EMPTY_STATIC_INIT(AXMethodCallsLogger)

FOUNDATION_EXPORT void AXMethodCallsLogger_init(AXMethodCallsLogger *self);

FOUNDATION_EXPORT AXMethodCallsLogger *new_AXMethodCallsLogger_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AXMethodCallsLogger *create_AXMethodCallsLogger_init(void);

J2OBJC_TYPE_LITERAL_HEADER(AXMethodCallsLogger)

@compatibility_alias AndroidxLifecycleMethodCallsLogger AXMethodCallsLogger;

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxLifecycleMethodCallsLogger")
