//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/lifecycle/lifecycle-common/src/main/java/androidx/lifecycle/OnLifecycleEvent.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxLifecycleOnLifecycleEvent")
#ifdef RESTRICT_AndroidxLifecycleOnLifecycleEvent
#define INCLUDE_ALL_AndroidxLifecycleOnLifecycleEvent 0
#else
#define INCLUDE_ALL_AndroidxLifecycleOnLifecycleEvent 1
#endif
#undef RESTRICT_AndroidxLifecycleOnLifecycleEvent

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXOnLifecycleEvent_) && (INCLUDE_ALL_AndroidxLifecycleOnLifecycleEvent || defined(INCLUDE_AXOnLifecycleEvent))
#define AXOnLifecycleEvent_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class AXLifecycle_Event;
@class IOSClass;

@protocol AXOnLifecycleEvent < JavaLangAnnotationAnnotation >

@property (readonly) AXLifecycle_Event *value;

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface AXOnLifecycleEvent : NSObject < AXOnLifecycleEvent > {
 @public
  AXLifecycle_Event *value_;
}

@end

J2OBJC_EMPTY_STATIC_INIT(AXOnLifecycleEvent)

FOUNDATION_EXPORT id<AXOnLifecycleEvent> create_AXOnLifecycleEvent(AXLifecycle_Event *value);

J2OBJC_TYPE_LITERAL_HEADER(AXOnLifecycleEvent)

#define AndroidxLifecycleOnLifecycleEvent AXOnLifecycleEvent

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxLifecycleOnLifecycleEvent")
