//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/lifecycle/lifecycle-common/src/main/java/androidx/lifecycle/SingleGeneratedAdapterObserver.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxLifecycleSingleGeneratedAdapterObserver")
#ifdef RESTRICT_AndroidxLifecycleSingleGeneratedAdapterObserver
#define INCLUDE_ALL_AndroidxLifecycleSingleGeneratedAdapterObserver 0
#else
#define INCLUDE_ALL_AndroidxLifecycleSingleGeneratedAdapterObserver 1
#endif
#undef RESTRICT_AndroidxLifecycleSingleGeneratedAdapterObserver

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXSingleGeneratedAdapterObserver_) && (INCLUDE_ALL_AndroidxLifecycleSingleGeneratedAdapterObserver || defined(INCLUDE_AXSingleGeneratedAdapterObserver))
#define AXSingleGeneratedAdapterObserver_

#define RESTRICT_AndroidxLifecycleLifecycleEventObserver 1
#define INCLUDE_AXLifecycleEventObserver 1
#include "androidx/lifecycle/LifecycleEventObserver.h"

@class AXLifecycle_Event;
@protocol AXGeneratedAdapter;
@protocol AXLifecycleOwner;

@interface AXSingleGeneratedAdapterObserver : NSObject < AXLifecycleEventObserver >

#pragma mark Public

- (void)onStateChangedWithAXLifecycleOwner:(id<AXLifecycleOwner> __nonnull)source
                     withAXLifecycle_Event:(AXLifecycle_Event * __nonnull)event;

#pragma mark Package-Private

- (instancetype __nonnull)initPackagePrivateWithAXGeneratedAdapter:(id<AXGeneratedAdapter>)generatedAdapter;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(AXSingleGeneratedAdapterObserver)

FOUNDATION_EXPORT void AXSingleGeneratedAdapterObserver_initPackagePrivateWithAXGeneratedAdapter_(AXSingleGeneratedAdapterObserver *self, id<AXGeneratedAdapter> generatedAdapter);

FOUNDATION_EXPORT AXSingleGeneratedAdapterObserver *new_AXSingleGeneratedAdapterObserver_initPackagePrivateWithAXGeneratedAdapter_(id<AXGeneratedAdapter> generatedAdapter) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AXSingleGeneratedAdapterObserver *create_AXSingleGeneratedAdapterObserver_initPackagePrivateWithAXGeneratedAdapter_(id<AXGeneratedAdapter> generatedAdapter);

J2OBJC_TYPE_LITERAL_HEADER(AXSingleGeneratedAdapterObserver)

@compatibility_alias AndroidxLifecycleSingleGeneratedAdapterObserver AXSingleGeneratedAdapterObserver;

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxLifecycleSingleGeneratedAdapterObserver")
