//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/lifecycle/lifecycle-livedata/src/main/java/androidx/lifecycle/Transformations.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxLifecycleTransformations")
#ifdef RESTRICT_AndroidxLifecycleTransformations
#define INCLUDE_ALL_AndroidxLifecycleTransformations 0
#else
#define INCLUDE_ALL_AndroidxLifecycleTransformations 1
#endif
#undef RESTRICT_AndroidxLifecycleTransformations

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXTransformations_) && (INCLUDE_ALL_AndroidxLifecycleTransformations || defined(INCLUDE_AXTransformations))
#define AXTransformations_

@class AXLiveData;
@protocol AXFunction;

@interface AXTransformations : NSObject

#pragma mark Public

+ (AXLiveData * __nonnull)distinctUntilChangedWithAXLiveData:(AXLiveData * __nonnull)source;

+ (AXLiveData * __nonnull)mapWithAXLiveData:(AXLiveData * __nonnull)source
                             withAXFunction:(id<AXFunction> __nonnull)mapFunction;

+ (AXLiveData * __nonnull)switchMapWithAXLiveData:(AXLiveData * __nonnull)source
                                   withAXFunction:(id<AXFunction> __nonnull)switchMapFunction;

@end

J2OBJC_EMPTY_STATIC_INIT(AXTransformations)

FOUNDATION_EXPORT AXLiveData *AXTransformations_mapWithAXLiveData_withAXFunction_(AXLiveData *source, id<AXFunction> mapFunction);

FOUNDATION_EXPORT AXLiveData *AXTransformations_switchMapWithAXLiveData_withAXFunction_(AXLiveData *source, id<AXFunction> switchMapFunction);

FOUNDATION_EXPORT AXLiveData *AXTransformations_distinctUntilChangedWithAXLiveData_(AXLiveData *source);

J2OBJC_TYPE_LITERAL_HEADER(AXTransformations)

@compatibility_alias AndroidxLifecycleTransformations AXTransformations;

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxLifecycleTransformations")
