//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/arch/core/core-runtime/src/main/java/androidx/arch/core/executor/TaskExecutor.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxArchCoreExecutorTaskExecutor")
#ifdef RESTRICT_AndroidxArchCoreExecutorTaskExecutor
#define INCLUDE_ALL_AndroidxArchCoreExecutorTaskExecutor 0
#else
#define INCLUDE_ALL_AndroidxArchCoreExecutorTaskExecutor 1
#endif
#undef RESTRICT_AndroidxArchCoreExecutorTaskExecutor

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXTaskExecutor_) && (INCLUDE_ALL_AndroidxArchCoreExecutorTaskExecutor || defined(INCLUDE_AXTaskExecutor))
#define AXTaskExecutor_

@protocol JavaLangRunnable;

@interface AXTaskExecutor : NSObject

#pragma mark Public

- (instancetype __nonnull)init;

- (void)executeOnDiskIOWithJavaLangRunnable:(id<JavaLangRunnable> __nonnull)runnable;

- (void)executeOnMainThreadWithJavaLangRunnable:(id<JavaLangRunnable> __nonnull)runnable;

- (jboolean)isMainThread;

- (void)postToMainThreadWithJavaLangRunnable:(id<JavaLangRunnable> __nonnull)runnable;

@end

J2OBJC_EMPTY_STATIC_INIT(AXTaskExecutor)

FOUNDATION_EXPORT void AXTaskExecutor_init(AXTaskExecutor *self);

J2OBJC_TYPE_LITERAL_HEADER(AXTaskExecutor)

@compatibility_alias AndroidxArchCoreExecutorTaskExecutor AXTaskExecutor;

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxArchCoreExecutorTaskExecutor")
