//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/arch/core/core-common/src/main/java/androidx/arch/core/internal/FastSafeIterableMap.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxArchCoreInternalFastSafeIterableMap")
#ifdef RESTRICT_AndroidxArchCoreInternalFastSafeIterableMap
#define INCLUDE_ALL_AndroidxArchCoreInternalFastSafeIterableMap 0
#else
#define INCLUDE_ALL_AndroidxArchCoreInternalFastSafeIterableMap 1
#endif
#undef RESTRICT_AndroidxArchCoreInternalFastSafeIterableMap

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXFastSafeIterableMap_) && (INCLUDE_ALL_AndroidxArchCoreInternalFastSafeIterableMap || defined(INCLUDE_AXFastSafeIterableMap))
#define AXFastSafeIterableMap_

#define RESTRICT_AndroidxArchCoreInternalSafeIterableMap 1
#define INCLUDE_AXSafeIterableMap 1
#include "androidx/arch/core/internal/SafeIterableMap.h"

@class AXSafeIterableMap_Entry;
@protocol JavaUtilMap_Entry;

@interface AXFastSafeIterableMap : AXSafeIterableMap

#pragma mark Public

- (instancetype __nonnull)init;

- (id<JavaUtilMap_Entry>)ceilWithId:(id)k;

- (jboolean)containsWithId:(id)key;

- (id)putIfAbsentWithId:(id __nonnull)key
                 withId:(id __nonnull)v;

- (id)removeWithId:(id __nonnull)key;

#pragma mark Protected

- (AXSafeIterableMap_Entry *)getWithId:(id)k;

#pragma mark Package-Private

@end

J2OBJC_EMPTY_STATIC_INIT(AXFastSafeIterableMap)

FOUNDATION_EXPORT void AXFastSafeIterableMap_init(AXFastSafeIterableMap *self);

FOUNDATION_EXPORT AXFastSafeIterableMap *new_AXFastSafeIterableMap_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AXFastSafeIterableMap *create_AXFastSafeIterableMap_init(void);

J2OBJC_TYPE_LITERAL_HEADER(AXFastSafeIterableMap)

@compatibility_alias AndroidxArchCoreInternalFastSafeIterableMap AXFastSafeIterableMap;

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxArchCoreInternalFastSafeIterableMap")
