//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: androidx/arch/core/core-common/src/main/java/androidx/arch/core/internal/SafeIterableMap.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_AndroidxArchCoreInternalSafeIterableMap")
#ifdef RESTRICT_AndroidxArchCoreInternalSafeIterableMap
#define INCLUDE_ALL_AndroidxArchCoreInternalSafeIterableMap 0
#else
#define INCLUDE_ALL_AndroidxArchCoreInternalSafeIterableMap 1
#endif
#undef RESTRICT_AndroidxArchCoreInternalSafeIterableMap
#ifdef INCLUDE_AXSafeIterableMap_IteratorWithAdditions
#define INCLUDE_AXSafeIterableMap_SupportRemove 1
#endif
#ifdef INCLUDE_AXSafeIterableMap_AscendingIterator
#define INCLUDE_AXSafeIterableMap_ListIterator 1
#endif
#ifdef INCLUDE_AXSafeIterableMap_ListIterator
#define INCLUDE_AXSafeIterableMap_SupportRemove 1
#endif

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (AXSafeIterableMap_) && (INCLUDE_ALL_AndroidxArchCoreInternalSafeIterableMap || defined(INCLUDE_AXSafeIterableMap))
#define AXSafeIterableMap_

#define RESTRICT_JavaLangIterable 1
#define INCLUDE_JavaLangIterable 1
#include "java/lang/Iterable.h"

@class AXSafeIterableMap_Entry;
@class AXSafeIterableMap_IteratorWithAdditions;
@protocol JavaUtilFunctionConsumer;
@protocol JavaUtilIterator;
@protocol JavaUtilMap_Entry;
@protocol JavaUtilSpliterator;

@interface AXSafeIterableMap : NSObject < JavaLangIterable > {
 @public
  AXSafeIterableMap_Entry *mStart_;
}

#pragma mark Public

- (instancetype __nonnull)init;

- (id<JavaUtilIterator>)descendingIterator;

- (id<JavaUtilMap_Entry>)eldest;

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

- (id<JavaUtilIterator> __nonnull)iterator;

- (AXSafeIterableMap_IteratorWithAdditions *)iteratorWithAdditions;

- (id<JavaUtilMap_Entry>)newest OBJC_METHOD_FAMILY_NONE;

- (id)putIfAbsentWithId:(id __nonnull)key
                 withId:(id __nonnull)v;

- (id)removeWithId:(id __nonnull)key;

- (jint)size;

- (NSString *)description;

#pragma mark Protected

- (AXSafeIterableMap_Entry *)getWithId:(id)k;

#pragma mark Package-Private

- (AXSafeIterableMap_Entry *)putWithId:(id __nonnull)key
                                withId:(id __nonnull)v;

@end

J2OBJC_EMPTY_STATIC_INIT(AXSafeIterableMap)

J2OBJC_FIELD_SETTER(AXSafeIterableMap, mStart_, AXSafeIterableMap_Entry *)

FOUNDATION_EXPORT void AXSafeIterableMap_init(AXSafeIterableMap *self);

FOUNDATION_EXPORT AXSafeIterableMap *new_AXSafeIterableMap_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AXSafeIterableMap *create_AXSafeIterableMap_init(void);

J2OBJC_TYPE_LITERAL_HEADER(AXSafeIterableMap)

@compatibility_alias AndroidxArchCoreInternalSafeIterableMap AXSafeIterableMap;

#endif

#if !defined (AXSafeIterableMap_SupportRemove_) && (INCLUDE_ALL_AndroidxArchCoreInternalSafeIterableMap || defined(INCLUDE_AXSafeIterableMap_SupportRemove))
#define AXSafeIterableMap_SupportRemove_

@class AXSafeIterableMap_Entry;

@interface AXSafeIterableMap_SupportRemove : NSObject

#pragma mark Package-Private

- (instancetype __nonnull)init;

- (void)supportRemoveWithAXSafeIterableMap_Entry:(AXSafeIterableMap_Entry * __nonnull)entry_;

@end

J2OBJC_EMPTY_STATIC_INIT(AXSafeIterableMap_SupportRemove)

FOUNDATION_EXPORT void AXSafeIterableMap_SupportRemove_init(AXSafeIterableMap_SupportRemove *self);

J2OBJC_TYPE_LITERAL_HEADER(AXSafeIterableMap_SupportRemove)

#endif

#if !defined (AXSafeIterableMap_ListIterator_) && (INCLUDE_ALL_AndroidxArchCoreInternalSafeIterableMap || defined(INCLUDE_AXSafeIterableMap_ListIterator))
#define AXSafeIterableMap_ListIterator_

#define RESTRICT_JavaUtilIterator 1
#define INCLUDE_JavaUtilIterator 1
#include "java/util/Iterator.h"

@class AXSafeIterableMap_Entry;
@protocol JavaUtilFunctionConsumer;
@protocol JavaUtilMap_Entry;

@interface AXSafeIterableMap_ListIterator : AXSafeIterableMap_SupportRemove < JavaUtilIterator > {
 @public
  AXSafeIterableMap_Entry *mExpectedEnd_;
  AXSafeIterableMap_Entry *mNext_;
}

#pragma mark Public

- (jboolean)hasNext;

- (id<JavaUtilMap_Entry>)next;

- (void)supportRemoveWithAXSafeIterableMap_Entry:(AXSafeIterableMap_Entry * __nonnull)entry_;

#pragma mark Package-Private

- (AXSafeIterableMap_Entry *)backwardWithAXSafeIterableMap_Entry:(AXSafeIterableMap_Entry *)entry_;

- (AXSafeIterableMap_Entry *)forwardWithAXSafeIterableMap_Entry:(AXSafeIterableMap_Entry *)entry_;

@end

J2OBJC_EMPTY_STATIC_INIT(AXSafeIterableMap_ListIterator)

J2OBJC_FIELD_SETTER(AXSafeIterableMap_ListIterator, mExpectedEnd_, AXSafeIterableMap_Entry *)
J2OBJC_FIELD_SETTER(AXSafeIterableMap_ListIterator, mNext_, AXSafeIterableMap_Entry *)

FOUNDATION_EXPORT void AXSafeIterableMap_ListIterator_initWithAXSafeIterableMap_Entry_withAXSafeIterableMap_Entry_(AXSafeIterableMap_ListIterator *self, AXSafeIterableMap_Entry *start, AXSafeIterableMap_Entry *expectedEnd);

J2OBJC_TYPE_LITERAL_HEADER(AXSafeIterableMap_ListIterator)

#endif

#if !defined (AXSafeIterableMap_AscendingIterator_) && (INCLUDE_ALL_AndroidxArchCoreInternalSafeIterableMap || defined(INCLUDE_AXSafeIterableMap_AscendingIterator))
#define AXSafeIterableMap_AscendingIterator_

@class AXSafeIterableMap_Entry;

@interface AXSafeIterableMap_AscendingIterator : AXSafeIterableMap_ListIterator

#pragma mark Package-Private

- (instancetype __nonnull)initWithAXSafeIterableMap_Entry:(AXSafeIterableMap_Entry *)start
                              withAXSafeIterableMap_Entry:(AXSafeIterableMap_Entry *)expectedEnd;

- (AXSafeIterableMap_Entry *)backwardWithAXSafeIterableMap_Entry:(AXSafeIterableMap_Entry *)entry_;

- (AXSafeIterableMap_Entry *)forwardWithAXSafeIterableMap_Entry:(AXSafeIterableMap_Entry *)entry_;

@end

J2OBJC_EMPTY_STATIC_INIT(AXSafeIterableMap_AscendingIterator)

FOUNDATION_EXPORT void AXSafeIterableMap_AscendingIterator_initWithAXSafeIterableMap_Entry_withAXSafeIterableMap_Entry_(AXSafeIterableMap_AscendingIterator *self, AXSafeIterableMap_Entry *start, AXSafeIterableMap_Entry *expectedEnd);

FOUNDATION_EXPORT AXSafeIterableMap_AscendingIterator *new_AXSafeIterableMap_AscendingIterator_initWithAXSafeIterableMap_Entry_withAXSafeIterableMap_Entry_(AXSafeIterableMap_Entry *start, AXSafeIterableMap_Entry *expectedEnd) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AXSafeIterableMap_AscendingIterator *create_AXSafeIterableMap_AscendingIterator_initWithAXSafeIterableMap_Entry_withAXSafeIterableMap_Entry_(AXSafeIterableMap_Entry *start, AXSafeIterableMap_Entry *expectedEnd);

J2OBJC_TYPE_LITERAL_HEADER(AXSafeIterableMap_AscendingIterator)

#endif

#if !defined (AXSafeIterableMap_IteratorWithAdditions_) && (INCLUDE_ALL_AndroidxArchCoreInternalSafeIterableMap || defined(INCLUDE_AXSafeIterableMap_IteratorWithAdditions))
#define AXSafeIterableMap_IteratorWithAdditions_

#define RESTRICT_JavaUtilIterator 1
#define INCLUDE_JavaUtilIterator 1
#include "java/util/Iterator.h"

@class AXSafeIterableMap;
@class AXSafeIterableMap_Entry;
@protocol JavaUtilFunctionConsumer;
@protocol JavaUtilMap_Entry;

@interface AXSafeIterableMap_IteratorWithAdditions : AXSafeIterableMap_SupportRemove < JavaUtilIterator >

#pragma mark Public

- (jboolean)hasNext;

- (id<JavaUtilMap_Entry>)next;

#pragma mark Package-Private

- (instancetype __nonnull)initWithAXSafeIterableMap:(AXSafeIterableMap *)outer$;

- (void)supportRemoveWithAXSafeIterableMap_Entry:(AXSafeIterableMap_Entry * __nonnull)entry_;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(AXSafeIterableMap_IteratorWithAdditions)

FOUNDATION_EXPORT void AXSafeIterableMap_IteratorWithAdditions_initWithAXSafeIterableMap_(AXSafeIterableMap_IteratorWithAdditions *self, AXSafeIterableMap *outer$);

FOUNDATION_EXPORT AXSafeIterableMap_IteratorWithAdditions *new_AXSafeIterableMap_IteratorWithAdditions_initWithAXSafeIterableMap_(AXSafeIterableMap *outer$) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AXSafeIterableMap_IteratorWithAdditions *create_AXSafeIterableMap_IteratorWithAdditions_initWithAXSafeIterableMap_(AXSafeIterableMap *outer$);

J2OBJC_TYPE_LITERAL_HEADER(AXSafeIterableMap_IteratorWithAdditions)

#endif

#if !defined (AXSafeIterableMap_Entry_) && (INCLUDE_ALL_AndroidxArchCoreInternalSafeIterableMap || defined(INCLUDE_AXSafeIterableMap_Entry))
#define AXSafeIterableMap_Entry_

#define RESTRICT_JavaUtilMap 1
#define INCLUDE_JavaUtilMap_Entry 1
#include "java/util/Map.h"

@interface AXSafeIterableMap_Entry : NSObject < JavaUtilMap_Entry > {
 @public
  id mKey_;
  id mValue_;
  AXSafeIterableMap_Entry *mNext_;
  AXSafeIterableMap_Entry *mPrevious_;
}

#pragma mark Public

- (jboolean)isEqual:(id)obj;

- (id __nonnull)getKey;

- (id __nonnull)getValue;

- (NSUInteger)hash;

- (id)setValueWithId:(id)value;

- (NSString *)description;

#pragma mark Package-Private

- (instancetype __nonnull)initWithId:(id __nonnull)key
                              withId:(id __nonnull)value;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(AXSafeIterableMap_Entry)

J2OBJC_FIELD_SETTER(AXSafeIterableMap_Entry, mKey_, id)
J2OBJC_FIELD_SETTER(AXSafeIterableMap_Entry, mValue_, id)
J2OBJC_FIELD_SETTER(AXSafeIterableMap_Entry, mNext_, AXSafeIterableMap_Entry *)
J2OBJC_FIELD_SETTER(AXSafeIterableMap_Entry, mPrevious_, AXSafeIterableMap_Entry *)

FOUNDATION_EXPORT void AXSafeIterableMap_Entry_initWithId_withId_(AXSafeIterableMap_Entry *self, id key, id value);

FOUNDATION_EXPORT AXSafeIterableMap_Entry *new_AXSafeIterableMap_Entry_initWithId_withId_(id key, id value) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT AXSafeIterableMap_Entry *create_AXSafeIterableMap_Entry_initWithId_withId_(id key, id value);

J2OBJC_TYPE_LITERAL_HEADER(AXSafeIterableMap_Entry)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_AndroidxArchCoreInternalSafeIterableMap")
